[package]
name = "fastpay"
version = "0.1.0"
authors = ["Libra <oncall+libra@xmail.facebook.com>"]
publish = false
edition = "2018"

[dependencies]
bytes = "0.5.4"
clap = "2.33.0"
env_logger = "0.7.1"
failure = "0.1.7"
futures = "0.3.4"
log = "0.4.8"
net2 = "0.2.33"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
tokio = { version = "0.2.16", features = ["full"] }

fastpay_core = { path = "../fastpay_core" }

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "bench"
path = "src/bench.rs"
